name: target_lint
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  analyzer: ^3.3.1
  analyzer_plugin: ^0.9.0
  custom_lint_builder:
    path: ../custom_lint_builder
  path: ^1.8.1
  recase: ^4.0.0