include: ../../../analysis_options.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    public_member_api_docs: false
    avoid_print: false
    unreachable_from_main: false

custom_lint:
  errors:
    riverpod_final_provider: error
