name: analyze app

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable
    steps:
      - uses: actions/checkout@v3
      - run: flutter pub get
        working-directory: packages/custom_lint_problem
      - run: flutter analyze
        working-directory: packages/custom_lint_problem
      - run: flutter pub run custom_lint
        working-directory: packages/custom_lint_problem
